baseURL = "http://shdobxr.github.io/cloudburns/"
languageCode = "en-us"
title = "Burned"
theme = "minimal"
googleAnalytics = ""

[params]
    publishDir = "docs"
    author = "D G"
    description = "Personal blog theme powered by Hugo"
    githubUsername = "#shdobxr"
    accent = "blue"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 2

[[menu.main]]
    url = "/project/"
    name = "Projects"
    weight = 3

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:me@example.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/shdobxr/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/shdobxr/"
    name = "twitter"
    weight = 3

#[[menu.icon]]
#    url = "https://www.linkedin.com/in/dan-girard-cissp-aws-asa-5945a34/"
#    name = "linkedin"
#    weight = 4

[[menu.icon]]
    url = "https://www.stackoverflow.com/username/"
    name = "stack-overflow"
    weight = 5
